export const StoreNames = {
    DESK_CARDS: 'DESK_CARDS',
    USER_CARDS: 'USER_CARDS',
    COLODA_CARDS: 'COLODA_CARDS',
    TRASH_CARDS: 'TRASH_CARDS',
    ROUND_CARDS: 'ROUND_CARDS',
    COMPUTER_CARDS: 'COMPUTER_CARDS',
}